**Description**:
The code applies variable transformation by deriving a new attribute, Cholesterol_Ratio, from two existing attributes: CholesterolTotal divided by CholesterolHDL. The original columns were kept unchanged.

**Justification**:
Total cholesterol and HDL each describe only part of a patient's lipid profile. Their ratio is a widely used clinical indicator of metabolic and cardiovascular risk, and it summarizes both measurements in a single meaningful value. Creating it gives the mining algorithms a more informative feature than either raw attribute alone.

**Preprocessing Result**: A new numeric attribute, Cholesterol_Ratio, was added, ranging from 1.57 to 14.41 with a mean of 4.55. The original attributes were preserved and the processed data was saved separately as Preprocessed_dataset.

**How it improved the dataset**:
The transformation combined two related measurements into one interpretable feature that captures the balance between total and "good" cholesterol, enriching the dataset for classification and clustering without losing any original information.

In [ ]:
import pandas as pd
raw_df=pd.read_csv("/diabetes_data.csv")
df = raw_df.copy()

In [ ]:
bins = [25, 40, 60, 91]
labels = ["Young", "Middle-Aged", "Senior"]

In [ ]:
df["Cholesterol_Ratio"] = df["CholesterolTotal"] / df["CholesterolHDL"]

In [ ]:
print("Raw dataset snapshot:")
print(raw_df[["PatientID", "CholesterolTotal", "CholesterolHDL", "Diagnosis"]].head(10))

Raw dataset snapshot:
   PatientID  CholesterolTotal  CholesterolHDL  Diagnosis
0       6000        254.270670       70.801469          1
1       6001        155.358831       39.900112          1
2       6002        231.608922       62.480666          0
3       6003        176.592374       46.977819          0
4       6004        157.344121       40.059755          0
5       6005        250.001898       24.705041          0
6       6006        258.393159       24.457787          0
7       6007        159.338689       39.448009          0
8       6008        168.147780       85.458363          1
9       6009        164.024326       55.621487          0


In [ ]:
print("\nPreprocessed dataset snapshot:")
print(df[["PatientID", "CholesterolTotal", "CholesterolHDL","Cholesterol_Ratio", "Diagnosis"]].head(10).round(3))


Preprocessed dataset snapshot:
   PatientID  CholesterolTotal  CholesterolHDL  Cholesterol_Ratio  Diagnosis
0       6000           254.271          70.801              3.591          1
1       6001           155.359          39.900              3.894          1
2       6002           231.609          62.481              3.707          0
3       6003           176.592          46.978              3.759          0
4       6004           157.344          40.060              3.928          0
5       6005           250.002          24.705             10.119          0
6       6006           258.393          24.458             10.565          0
7       6007           159.339          39.448              4.039          0
8       6008           168.148          85.458              1.968          1
9       6009           164.024          55.621              2.949          0


In [ ]:
print("\nCholesterol_Ratio summary:")
print(df["Cholesterol_Ratio"].describe().round(2))


Cholesterol_Ratio summary:
count    1879.00
mean        4.55
std         2.44
min         1.57
25%         2.80
50%         3.72
75%         5.75
max        14.41
Name: Cholesterol_Ratio, dtype: float64


In [ ]:
import os

os.makedirs('Dataset', exist_ok=True)
df.to_csv('Dataset/Preprocessed_dataset.csv', index=False)
print("Saved complete preprocessed dataset to Dataset/Preprocessed_dataset.csv")

Saved complete preprocessed dataset to Dataset/Preprocessed_dataset.csv


**3-Variabale Transformation**

**Description**: The code applies variable transformation by deriving a new attribute, Cholesterol_Ratio, from two existing attributes: CholesterolTotal divided by CholesterolHDL. The original columns were kept unchanged.



**Justification**:
Total cholesterol and HDL each describe only part of a patient's lipid profile. Their ratio is a widely used clinical indicator of metabolic and cardiovascular risk, and it summarizes both measurements in a single meaningful value. Creating it gives the mining algorithms a more informative feature than either raw attribute alone.



**Preprocessing Result**: A new numeric attribute, Cholesterol_Ratio, was added, ranging from 1.57 to 14.41 with a mean of 4.55. The original attributes were preserved and the processed data was saved separately as Preprocessed_dataset.



**How it improved the dataset**: The transformation combined two related measurements into one interpretable feature that captures the balance between total and "good" cholesterol, enriching the dataset for classification and clustering without losing any original information.

In [3]:
import pandas as pd
raw_df=pd.read_csv("/diabetes_data.csv")
df = raw_df.copy()

FileNotFoundError: [Errno 2] No such file or directory: '/diabetes_data.csv'

In [ ]:
df["Cholesterol_Ratio"] = df["CholesterolTotal"] / df["CholesterolHDL"]

In [ ]:
print("Raw dataset snapshot:")
print(raw_df[["PatientID", "CholesterolTotal", "CholesterolHDL", "Diagnosis"]].head(10))

In [ ]:
print("\nPreprocessed dataset snapshot:")
print(df[["PatientID", "CholesterolTotal", "CholesterolHDL","Cholesterol_Ratio", "Diagnosis"]].head(10).round(3))

In [ ]:
print("\nCholesterol_Ratio summary:")
print(df["Cholesterol_Ratio"].describe().round(2))

In [ ]:
import os

os.makedirs('Dataset', exist_ok=True)
df.to_csv('Dataset/Preprocessed_dataset.csv', index=False)
print("Saved complete preprocessed dataset to Dataset/Preprocessed_dataset.csv")